export const chatState = {
  _searchQuery: '',
  _usersCache: null,
  _latestChatMap: {},
  _watcherPromise: null,
  _noticeUnsub: null,
  _loadNoticeFn: null,
  _presenceRepaintTick: null,
  _latestNotice: null,
  _contactsUnsub: null,
  _myContacts: new Set(),
  _groupsListenerAttached: false,
  _otherUserAvi: '',
  _otherUserUid: '',
  _peerUserUnsub: null,
  _peerStatusTick: null,
  _peerLastSeenAt: null,
  _chatDocUnsub: null,
  _peerTyping: false,
  _onPeerTyping: () => {},
  _iAmTyping: false,
  _typingTimeout: null,
  _typingCh: null,
  _typingChReady: false,
  _seenMsgIdsChatId: null,
  _seenMsgIds: new Set(),
  _seenBaselineDone: false,
  _msgAnimStart: new Map(),
  _dissolving: new Map(),
  _readObs: null,
  _pendingReadIds: new Set(),
  _readFlushTimer: null,
  _locallyReadIds: new Set(),
  _pendingPostShare: null,
  _rt: null,
  _rtChatId: null,
  _rtLocal: new Map(),
  _rtRead: new Set(),
  _threadUnsub: null,
  _reloadThread: null,
  _curMsgs: [],
  _chatSelFile: null,
  _chatsUnsub: null,
  _postExistenceMap: new Map(),
  _userExistenceMap: new Map(),
};

export const chatUI = {};
